name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: manual deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: sshagent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: deploy
        run: |
          branch="${GITHUB_REF#refs/heads/}"
          echo "The branched that was pushed is $branch"
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "34.45.225.35 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKBG6Jd3oQtb6BIKsn9AiM/n17jN1cAOCjnUs+tP3ldxJLjyJ4Tlsn1X3Y2u0WYPoZGCP6JfCX0ufUJSO/t3h6s=" >> ~/.ssh/known_hosts
          echo "34.45.225.35 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJLObApLUESHu3CBrospUQm4Ao1XTGMKIBt2hpd3/4v7Gn9r8hGGM+8HETfRBDm2Z685govEMpqpqvp3SGxZn2+Z1VTzUirzQaxMGU1kT2o7ubYAH2/AYoCRB6uKLsJ+lE1M4iz57i36VH4nfzABivtQa7+gDpcV3GENmVINmwtPW7WGEwBfs6Uy5QGfHuvmBuRF7stie8XVUmUtqeHM38bZ3hlbe9ig+ajh6WFV6DgnHTL3wWAn1TNuow1QaJWx+1cBDpMhTB747PFxmSp1QEE10OaHAn1837vk+yc5a5y30JUBITU/XokIfCsw6+nXLocPNxENifrwM4EVmO+SxUfdszO6dyNI9dyLKy0D8wWmkzB1kYfeG7xbXUV0xuJTGOvwB4m0bsxheINvnmaNWdKS2BgpGcda4/EWc65xS+LqIPkteEcXViqMTr6Rq0b3+OiXAZC+gCpIuJ+XgR7wpDDgL7oILgH8KTY1KcuMtH8vpuRemZ6jNwajj6V1h1bMM=" >> ~/.ssh/known_hosts
          echo "34.45.225.35 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhrofi+ibNzyt5h8AAhaqdi9qU+Xtt9DxpGUwZhTNR/" >> ~/.ssh/known_hosts
          ssh root@34.45.225.35 <<EOF
            date > iwashere
            screen -ls | grep -q '\.api\s' && screen -S api -X quit
            screen -ls | grep -q '\.api\s' && screen -S api -X kill
            cd self-analyzation
            GIT_SSH_COMMAND="ssh -i /root/.ssh/id_rsa" git pull origin $branch
            cd ..
            screen -dmS api bash -c 'source saw/bin/activate; cd self-analyzation; pip install -r requirements.txt; uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'
          EOF
