name: test
on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Start MongoDB in Docker
        run: |
          docker run -d -p 27017:27017 --name mongodb mongo:latest
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest tests/authentication
          pytest tests/mongodb
          pytest tests/conversations
